before_install:
  - sudo apt-get update --fix-missing
install:
  - pip install six
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
script:
  - python tests/test_AudioDataSourceFactory.py
